from pathlib import Path
r=Path('.')
a=r/'app/src/main/assets'
h=(a/'index.html').read_text(); j=(a/'app.js').read_text(); c=(a/'app.css').read_text()
def R(s,o,n):
    if o not in s: raise SystemExit('missing:'+o[:60].replace('\n',' '))
    return s.replace(o,n,1)
# quick bar: remove from page top, put under Meta tool row
old='''                <div id="quickTradeBar" class="quick-trade-bar" aria-label="التداول السريع">\n                    <button id="quickSell" class="quick-side quick-sell" type="button">\n                        <span>SELL</span><strong id="quickSellPrice" dir="ltr">—</strong>\n                    </button>\n                    <div class="quick-lot">\n                        <button id="quickLotDown" type="button" aria-label="تقليل اللوت">⌄</button>\n                        <input id="quickLot" type="number" min="0.01" max="100" step="0.01" value="0.10" inputmode="decimal" aria-label="حجم اللوت" dir="ltr">\n                        <button id="quickLotUp" type="button" aria-label="زيادة اللوت">⌃</button>\n                    </div>\n                    <button id="quickBuy" class="quick-side quick-buy" type="button">\n                        <span>BUY</span><strong id="quickBuyPrice" dir="ltr">—</strong>\n                    </button>\n                </div>\n\n'''
h=R(h,old,'')
h=R(h,'<button id="indicatorMenuButton" class="meta-tool indicator-menu-button" type="button" aria-label="فتح قائمة المؤشرات" title="المؤشرات"><span>ƒ</span></button>','''<button id="indicatorMenuButton" class="meta-tool indicator-menu-button" type="button" aria-label="Indicators" title="Indicators"><span>ƒ</span></button>\n                            <button id="accountMenuButton" class="meta-tool account-tool" type="button" aria-label="Accounts" title="Accounts"><span>☰</span></button>\n                            <div id="accountPopover" class="account-popover hidden"><div class="account-popover-head"><strong>Accounts</strong><button id="addAccountFromMenu" type="button">+ Add</button></div><div id="accountMenuList"></div></div>''')
h=R(h,'                        </div>\n                        <div class="chart-wrap" id="liveChartWrap">','''                        </div>\n                        <div id="quickTradeBar" class="quick-trade-bar compact-quick-trade" aria-label="Quick trading">\n                            <button id="quickSell" class="quick-side quick-sell" type="button"><span>SELL</span><strong id="quickSellPrice" dir="ltr">—</strong></button>\n                            <div class="quick-lot" dir="ltr"><button id="quickLotDown" type="button">−</button><label><small>LOT</small><input id="quickLot" type="text" value="0.10" inputmode="decimal" dir="ltr" autocomplete="off"></label><button id="quickLotUp" type="button">+</button></div>\n                            <button id="quickBuy" class="quick-side quick-buy" type="button"><span>BUY</span><strong id="quickBuyPrice" dir="ltr">—</strong></button>\n                        </div>\n                        <div class="chart-wrap" id="liveChartWrap">''')
# hide old New Order control but keep DOM for old listener compatibility
h=R(h,'<button id="newOrderButton" class="new-order-button" type="button">+ أمر جديد</button>','<button id="newOrderButton" class="new-order-button hidden" type="button" aria-hidden="true">+ أمر جديد</button>')
# v1.19 account functions override old single-account functions before event binding
block=r'''
    /* v1.19 multi-account manager */
    STORAGE.accounts='xauLab.accounts.v1'; STORAGE.activeAccount='xauLab.activeAccount.v1';
    state.accounts=[]; state.accountCreating=false;
    function persistAccountsV119(){try{localStorage.setItem(STORAGE.accounts,JSON.stringify(state.accounts||[]));if(state.account){localStorage.setItem(STORAGE.activeAccount,state.account.id);localStorage.setItem(STORAGE.account,JSON.stringify(state.account));}else{localStorage.removeItem(STORAGE.activeAccount);localStorage.removeItem(STORAGE.account);}}catch(e){}}
    function renderAccountMenu(){var box=byId('accountMenuList');if(!box)return;var xs=state.accounts||[];box.innerHTML=xs.length?xs.map(function(x){var on=state.account&&x.id===state.account.id;return '<div class="account-menu-row'+(on?' active':'')+'"><button type="button" data-account="'+escapeHtml(x.id)+'"><b>'+escapeHtml(x.name)+'</b><small dir="ltr">'+formatAccountMoney(x.balance)+' USD • 1:'+x.leverage+'</small></button><button type="button" class="del" data-del-account="'+escapeHtml(x.id)+'">×</button></div>';}).join(''):'<div class="account-menu-empty">No accounts yet</div>';}
    function loadAccount(){var xs=safeJsonParse(localStorage.getItem(STORAGE.accounts),null),old=sanitizeAccount(safeJsonParse(localStorage.getItem(STORAGE.account),null));state.accounts=Array.isArray(xs)?xs.map(sanitizeAccount).filter(Boolean):[];if(!state.accounts.length&&old)state.accounts=[old];var id=String(localStorage.getItem(STORAGE.activeAccount)||'');state.account=state.accounts.filter(function(x){return x.id===id;})[0]||state.accounts[0]||null;persistAccountsV119();syncAccountControls();updateAccountUi();renderAccountMenu();return state.account;}
    function persistAccountNow(){clearTimeout(state.accountPersistTimer);state.accountPersistTimer=null;if(state.account){state.account.updatedAt=Date.now();var hit=false;state.accounts=(state.accounts||[]).map(function(x){if(x.id===state.account.id){hit=true;return state.account;}return x;});if(!hit)state.accounts.push(state.account);}persistAccountsV119();renderAccountMenu();}
    function scheduleAccountPersist(){clearTimeout(state.accountPersistTimer);state.accountPersistTimer=setTimeout(persistAccountNow,180);}
    function updateAccountUi(){var x=state.account,s=byId('settingsAccountSummary'),tn=byId('tradeAccountName'),tm=byId('tradeAccountMeta'),hn=byId('historyAccountName'),hm=byId('historyAccountMeta');if(!x){if(s)s.textContent='No active account';if(tn)tn.textContent='No active account';if(tm)tm.textContent='Open Accounts to add or select';if(hn)hn.textContent='No active account';if(hm)hm.textContent='XAU Lab Demo';renderAccountMenu();return;}var meta='XAU Lab Demo • 1:'+x.leverage;if(s)s.textContent=x.name+' • '+formatAccountMoney(x.balance)+' USD • 1:'+x.leverage;if(tn)tn.textContent=x.name;if(tm)tm.textContent=meta;if(hn)hn.textContent=x.name;if(hm)hm.textContent=meta;renderAccountMenu();}
    function showAccountGate(editing,creating){state.accountEditing=!!editing;state.accountCreating=!!creating||(!state.account&&!editing);var x=state.accountCreating?null:state.account;byId('accountGateTitle').textContent=state.accountCreating?'إضافة حساب جديد':'إعدادات الحساب';byId('accountGateText').textContent=state.accountCreating?'أنشئ حساب Demo جديدًا، ثم بدّل بين حساباتك من Accounts أعلى الشارت.':'عدّل هذا الحساب فقط. تغيير رأس المال يعيد رصيده وسجله.';byId('accountName').value=x?x.name:'';byId('accountBalance').value=String(round(x?x.initialBalance:10000,2));byId('accountLeverage').value=String(x?x.leverage:100);byId('saveAccountButton').textContent=state.accountCreating?'إنشاء الحساب':'حفظ التعديلات';byId('cancelAccountEdit').classList.toggle('hidden',!state.accounts.length);byId('accountGate').classList.remove('hidden');document.body.classList.add('account-dialog-open');}
    function hideAccountGate(){if(!state.account&&!state.accounts.length)return;byId('accountGate').classList.add('hidden');document.body.classList.remove('account-dialog-open');state.accountEditing=false;state.accountCreating=false;}
    function saveAccountFromGate(){var name=byId('accountName').value.trim(),capital=Math.max(100,number(toEnglishDigits(byId('accountBalance').value),10000)),lev=clamp(Math.round(number(toEnglishDigits(byId('accountLeverage').value),100)),1,1000);if(!name){showToast('اكتب اسمًا للحساب','error');return;}var x=state.accountCreating?null:state.account,reset=!!(x&&Math.abs(x.initialBalance-capital)>.0001);if(!x){x=sanitizeAccount({id:'demo-'+Date.now()+'-'+Math.floor(Math.random()*9999),name:name,initialBalance:capital,balance:capital,equity:capital,freeMargin:capital,leverage:lev});state.accounts.push(x);state.account=x;}else{x.name=name;x.leverage=lev;if(reset){x.initialBalance=capital;x.balance=capital;x.equity=capital;x.freeMargin=capital;x.margin=0;x.floating=0;x.trades=[];x.manualPositions=[];x.pendingOrders=[];x.openTrade=null;}state.account=sanitizeAccount(x);}persistAccountNow();syncAccountControls();updateAccountUi();hideAccountGate();refreshManualOverlay(true);renderRobotTerminal();showToast(reset?'تم تحديث الحساب وإعادة ضبطه':'تم حفظ الحساب','success');}
    function switchAccountV119(id){persistAccountNow();var x=(state.accounts||[]).filter(function(a){return a.id===id;})[0];if(!x)return;state.account=x;state.lastResults=null;state.visualRobot=null;state.selectedManualTicket=null;persistAccountsV119();syncAccountControls();updateAccountUi();refreshManualOverlay(true);renderRobotTerminal();updateQuickTradeBar(currentManualQuote());showToast('Active: '+x.name,'success');}
    function deleteAccountV119(id){var x=(state.accounts||[]).filter(function(a){return a.id===id;})[0];if(!x)return;state.accounts=state.accounts.filter(function(a){return a.id!==id;});if(state.account&&state.account.id===id)state.account=state.accounts[0]||null;persistAccountsV119();syncAccountControls();updateAccountUi();refreshManualOverlay(true);renderRobotTerminal();showToast('تم حذف الحساب','success');}
    function saveQuickLotV119(){var i=byId('quickLot'),v=clamp(number(toEnglishDigits(i.value),state.account?state.account.lastLot:.10),.01,100);v=Math.round(v*100)/100;i.value=v.toFixed(2);if(state.account){state.account.lastLot=v;scheduleAccountPersist();}}
'''
j=R(j,'    function bindEvents() {',block+'\n    function bindEvents() {')
# bind new account manager and persist LOT after old +/- listeners run
anchor="        byId('quickPendingButton').addEventListener('click', function () { openManualOrderModal('buyLimit'); });"
extra=r'''        byId('quickLotDown').addEventListener('click',saveQuickLotV119);
        byId('quickLotUp').addEventListener('click',saveQuickLotV119);
        byId('quickLot').addEventListener('input',function(){this.value=toEnglishDigits(this.value).replace(/[^0-9.]/g,'');});
        byId('quickLot').addEventListener('blur',saveQuickLotV119);
        byId('accountMenuButton').addEventListener('click',function(e){var p=byId('accountPopover');renderAccountMenu();p.classList.toggle('hidden');e.stopPropagation();});
        byId('addAccountFromMenu').addEventListener('click',function(){byId('accountPopover').classList.add('hidden');showAccountGate(false,true);});
        byId('accountMenuList').addEventListener('click',function(e){var d=e.target.closest('[data-del-account]');if(d){deleteAccountV119(d.getAttribute('data-del-account'));return;}var b=e.target.closest('[data-account]');if(b){switchAccountV119(b.getAttribute('data-account'));byId('accountPopover').classList.add('hidden');}});
'''
j=R(j,anchor,extra+anchor)
# settings Account becomes add if none, edit if active
j=R(j,"byId('editAccountButton').addEventListener('click', function () { showAccountGate(true); });","byId('editAccountButton').addEventListener('click',function(){showAccountGate(!!state.account,!state.account);});")
# readable light-mode errors
c+=r'''
/* v1.19 */
.lab-pane .meta-compact-toolbar{direction:ltr;justify-content:flex-start;gap:6px;padding:6px 8px}.lab-pane .timeframe-compact{margin-right:0}.account-tool{font-size:20px}.compact-quick-trade{min-height:56px;border-top:1px solid var(--line);grid-template-columns:minmax(0,1fr) 126px minmax(0,1fr)}.compact-quick-trade .quick-side{padding:6px 12px}.compact-quick-trade .quick-side strong{font-size:18px}.compact-quick-trade .quick-lot{grid-template-columns:32px 1fr 32px}.quick-lot label{height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center}.quick-lot small{font:700 7px Arial;color:#65778a;letter-spacing:.7px}.quick-lot input{font-family:Arial,sans-serif!important;direction:ltr!important;font-variant-numeric:tabular-nums}.quick-lot button{font-family:Arial,sans-serif;font-size:21px}
.account-popover{position:absolute;z-index:130;top:52px;right:8px;width:min(300px,calc(100vw - 20px));max-height:55vh;overflow:auto;padding:7px;border:1px solid #31465d;border-radius:12px;background:#0b192a;box-shadow:0 14px 34px rgba(0,0,0,.38)}.account-popover-head{display:flex;direction:ltr;align-items:center;justify-content:space-between;padding:4px 4px 8px}.account-popover-head strong{color:#fff}.account-popover-head button{border:0;border-radius:8px;background:#2f80ed;color:#fff;padding:7px 10px;font-weight:800}.account-menu-row{display:grid;grid-template-columns:1fr 34px;gap:5px;margin:5px 0;padding:4px;border:1px solid #294158;border-radius:9px;background:#102238}.account-menu-row.active{border-color:#2f80ed}.account-menu-row>button:first-child{border:0;background:transparent;color:#eef4fa;text-align:right;padding:6px}.account-menu-row b,.account-menu-row small{display:block}.account-menu-row small{margin-top:3px;color:#8fa3b8;font:8px Arial}.account-menu-row .del{border:0;border-radius:7px;background:#341b25;color:#ff6c7d;font-size:18px}.account-menu-empty{padding:20px;text-align:center;color:#8fa3b8}.toast.error{color:#fff!important;background:#651b2a!important;border-color:#a84355!important;font-size:11px;font-weight:800}.toast.success{color:#fff!important;background:#0f5a48!important}body.light .toast.error,body.light .toast.success{color:#fff!important}body.light .account-popover{background:#fff;border-color:#ccd7e2}body.light .account-menu-row{background:#f4f7fa;border-color:#d7e0e8}body.light .account-menu-row>button:first-child{color:#18314b}
'''
(a/'index.html').write_text(h);(a/'app.js').write_text(j);(a/'app.css').write_text(c)
g=(r/'app/build.gradle').read_text().replace('versionCode 19','versionCode 20').replace("versionName '1.18.0'","versionName '1.19.0'")
if 'versionCode 20' not in g: raise SystemExit('version')
(r/'app/build.gradle').write_text(g)
print('v1.19 applied')
