package com.masari.personalplan;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.res.ColorStateList;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RectF;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.FrameLayout;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public class MasariProActivity extends Activity {
    private static final int BG=Color.rgb(247,249,252), WHITE=Color.WHITE, NAVY=Color.rgb(8,43,68), NAVY2=Color.rgb(14,57,86);
    private static final int GREEN=Color.rgb(24,142,78), GREEN2=Color.rgb(38,169,96), TEXT=Color.rgb(25,34,45), MUTED=Color.rgb(111,121,135), BORDER=Color.rgb(229,233,240);
    private static final int GOLD=Color.rgb(226,157,38), BLUE=Color.rgb(57,117,205), ORANGE=Color.rgb(230,139,45), RED=Color.rgb(210,81,73), PURPLE=Color.rgb(129,87,188), TEAL=Color.rgb(49,156,164), PINK=Color.rgb(202,91,136);
    private SharedPreferences prefs;
    private String tab="home", rewardTab="level", taskFilter="الكل", todayKey;
    private final LinkedHashMap<String,Integer> domainColors=new LinkedHashMap<>();

    static class T { String id,title,domain,icon; int start,end,points; boolean required; T(String i,int s,int e,String t,String d,int p,boolean r,String x){id=i;start=s;end=e;title=t;domain=d;points=p;required=r;icon=x;} }

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(WHITE);getWindow().setNavigationBarColor(NAVY);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);prefs=getSharedPreferences("masari_data",MODE_PRIVATE);todayKey=dateKey(Calendar.getInstance());setupDomains();migrateRewards();syncRewardCredits();render();}
    @Override protected void onResume(){super.onResume();if(prefs!=null){todayKey=dateKey(Calendar.getInstance());syncRewardCredits();render();}}

    private void setupDomains(){domainColors.put("القرآن",GREEN);domainColors.put("الإنجليزية والقبول",BLUE);domainColors.put("العمل والدخل",ORANGE);domainColors.put("الصحة",RED);domainColors.put("المعرفة والقراءة",PURPLE);domainColors.put("التواصل",TEAL);domainColors.put("الأسرة",PINK);domainColors.put("الدين والمسجد",Color.rgb(61,126,78));domainColors.put("الانضباط",Color.rgb(95,105,118));}
    private void migrateRewards(){if(!prefs.getBoolean("credits_migrated_v10",false)){int old=prefs.getInt("reward_stars",0);prefs.edit().putInt("reward_credits",prefs.getInt("reward_credits",0)+old*10).putBoolean("credits_migrated_v10",true).apply();}}

    private void render(){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(BG);shell.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);FrameLayout body=new FrameLayout(this);shell.addView(body,new LinearLayout.LayoutParams(-1,0,1));View screen;switch(tab){case"tasks":screen=tasksScreen();break;case"stats":screen=statsScreen();break;case"rewards":screen=rewardsScreen();break;case"more":screen=moreScreen();break;default:screen=homeScreen();}body.addView(screen,new FrameLayout.LayoutParams(-1,-1));shell.addView(bottomNav(),new LinearLayout.LayoutParams(-1,dp(76)));setContentView(shell);}

    private View homeScreen(){ScrollView s=scroll();LinearLayout r=root(s);topBar(r,"مساري","☰","♧");
        LinearLayout welcome=new LinearLayout(this);welcome.setOrientation(LinearLayout.HORIZONTAL);welcome.setGravity(Gravity.CENTER_VERTICAL);welcome.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);LinearLayout wt=new LinearLayout(this);wt.setOrientation(LinearLayout.VERTICAL);wt.addView(text("مرحبًا 👋",20,TEXT,true));wt.addView(text(homeMessage(),12,MUTED,false));welcome.addView(wt,new LinearLayout.LayoutParams(0,-2,1));welcome.addView(circle("م",50,Color.rgb(233,246,238),GREEN,20));add(r,welcome,12);
        section(r,"تقدمك","اليوم حتى الآن");LinearLayout p=card();p.setPadding(dp(14),dp(14),dp(14),dp(12));add(r,p,7);LinearLayout rings=new LinearLayout(this);rings.setOrientation(LinearLayout.HORIZONTAL);rings.setGravity(Gravity.CENTER);rings.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);miniRing(rings,"اليوم",dayRate(Calendar.getInstance()),GREEN);miniRing(rings,"الأسبوع",weekRate(),BLUE);miniRing(rings,"الشهر",monthRate(),PURPLE);miniRing(rings,"السنة",yearRate(),GOLD);p.addView(rings);
        int rate=dayRate(Calendar.getInstance());TextView hint=center(rate>=100?"اكتمل هدف اليوم — ممتاز 👏":rate>=80?"يوم قوي. أنجز ما بقي بهدوء.":"ركز على المهمة التالية فقط؛ لا تحتاج لإنهاء كل شيء دفعة واحدة.",11,rate>=80?GREEN:MUTED,true);hint.setPadding(0,dp(7),0,0);p.addView(hint);
        LinearLayout goal=card();goal.setPadding(dp(14),dp(13),dp(14),dp(13));add(r,goal,10);LinearLayout gh=new LinearLayout(this);gh.setOrientation(LinearLayout.HORIZONTAL);gh.setGravity(Gravity.CENTER_VERTICAL);gh.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);gh.addView(circle("◎",44,Color.rgb(232,247,238),GREEN,22));LinearLayout gtx=new LinearLayout(this);gtx.setOrientation(LinearLayout.VERTICAL);gtx.setPadding(dp(10),0,dp(8),0);gtx.addView(text("هدف اليوم",16,TEXT,true));gtx.addView(text("أكمل ٨٠٪ من نقاط المهام الأساسية، مع القرآن والإنجليزية.",11,MUTED,false));gh.addView(gtx,new LinearLayout.LayoutParams(0,-2,1));goal.addView(gh);TextView ds=text(ar(countDoneToday())+" من "+ar(tasksToday().size())+" مهام",11,GREEN,true);ds.setPadding(0,dp(8),0,dp(4));goal.addView(ds);goal.addView(progress(dayPoints(Calendar.getInstance()),dayTarget(Calendar.getInstance()),GREEN));
        section(r,"جدول اليوم","عرض الكل");int shown=0;for(T t:tasksToday()){if(t.id.equals("lunch")||t.id.equals("sleep2")||t.start<420)continue;compactTask(r,t);if(++shown==6)break;}
        LinearLayout streak=card();streak.setPadding(dp(14),dp(12),dp(14),dp(12));add(r,streak,10);LinearLayout st=new LinearLayout(this);st.setOrientation(LinearLayout.HORIZONTAL);st.setGravity(Gravity.CENTER_VERTICAL);st.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);LinearLayout sx=new LinearLayout(this);sx.setOrientation(LinearLayout.VERTICAL);sx.addView(text("🔥 سلسلة الأيام القوية",15,TEXT,true));sx.addView(text(ar(streak())+" يومًا متتاليًا بنسبة ٨٠٪ فأكثر",11,GREEN,true));st.addView(sx,new LinearLayout.LayoutParams(0,-2,1));st.addView(text(flames(streak()),19,GOLD,false));streak.addView(st);
        LinearLayout quick=new LinearLayout(this);quick.setOrientation(LinearLayout.HORIZONTAL);quick.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);quick.setPadding(0,dp(10),0,0);quick.addView(quick("📖","القرآن",GREEN),weight());quick.addView(quick("🎧","الإنجليزية",BLUE),weight());quick.addView(quick("▣","العمل",ORANGE),weight());quick.addView(quick("📚","LeapAhead",PURPLE),weight());r.addView(quick);return s;}

    private View tasksScreen(){ScrollView s=scroll();LinearLayout r=root(s);topBar(r,"المهام","⋮","⌕");weekStrip(r);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout chips=new LinearLayout(this);chips.setOrientation(LinearLayout.HORIZONTAL);chips.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);chips.setPadding(0,dp(11),0,dp(9));String[] fs={"الكل","قرآن","إنجليزية","عمل","صحة","قراءة","أسرة"};for(String f:fs){TextView c=chip(f,taskFilter.equals(f));chips.addView(c);c.setOnClickListener(v->{taskFilter=f;render();});}hs.addView(chips);r.addView(hs);
        LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.HORIZONTAL);h.setGravity(Gravity.CENTER_VERTICAL);h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);h.addView(text("مهام اليوم",19,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));h.addView(pill(ar(countDoneToday())+" / "+ar(tasksToday().size()),GREEN,Color.rgb(236,248,241)));r.addView(h);
        for(T t:tasksToday())if(matches(t))fullTask(r,t);Button add=button("＋ إضافة مهمة مخصصة",GREEN);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(52));ap.setMargins(0,dp(15),0,dp(8));r.addView(add,ap);add.setOnClickListener(v->startActivity(new Intent(this,PlannerCenterActivity.class)));return s;}

    private View statsScreen(){ScrollView s=scroll();LinearLayout r=root(s);topBar(r,"الإحصائيات","⋮","▦");
        LinearLayout summary=card();summary.setPadding(dp(14),dp(14),dp(14),dp(14));add(r,summary,10);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.setGravity(Gravity.CENTER);row.addView(bigRing(monthRate(),"التزام الشهر",GREEN),new LinearLayout.LayoutParams(0,dp(140),1));LinearLayout nums=new LinearLayout(this);nums.setOrientation(LinearLayout.VERTICAL);nums.setPadding(dp(10),0,dp(10),0);nums.addView(stat(ar(monthCompleted()),"مهمة مكتملة",GREEN));nums.addView(stat(ar(monthPlanned()),"مهمة مخططة",NAVY));nums.addView(stat(ar(monthStrongDays()),"يوم قوي",GOLD));row.addView(nums,new LinearLayout.LayoutParams(0,-2,1));summary.addView(row);
        section(r,"أداء آخر ٦ أسابيع","النسبة لكل أسبوع");LinearLayout bc=card();bc.setPadding(dp(8),dp(12),dp(8),dp(8));add(r,bc,6);bc.addView(new WeekBars(this),new LinearLayout.LayoutParams(-1,dp(190)));
        section(r,"اتجاه آخر ٣٠ يومًا","");LinearLayout tc=card();tc.setPadding(dp(8),dp(12),dp(8),dp(8));add(r,tc,6);tc.addView(new Trend(this),new LinearLayout.LayoutParams(-1,dp(185)));
        section(r,"تقدم المجالات","حسب نقاطك الفعلية");LinearLayout domains=card();domains.setPadding(dp(13),dp(12),dp(13),dp(12));add(r,domains,6);for(String d:domainColors.keySet())domainRow(domains,d);
        LinearLayout metrics1=new LinearLayout(this);metrics1.setOrientation(LinearLayout.HORIZONTAL);metrics1.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);metrics1.setPadding(0,dp(10),0,0);metrics1.addView(metric("★",ar(totalPoints()),"نقاط التقدم",GOLD),weight());metrics1.addView(metric("◷",formatHours(focusMinutes()),"تركيز هذا الشهر",BLUE),weight());metrics1.addView(metric("🔥",ar(streak()),"السلسلة",ORANGE),weight());r.addView(metrics1);
        LinearLayout metrics2=new LinearLayout(this);metrics2.setOrientation(LinearLayout.HORIZONTAL);metrics2.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);metrics2.setPadding(0,dp(7),0,0);metrics2.addView(metric("✓",ar(monthRate())+"٪","الالتزام",GREEN),weight());metrics2.addView(metric("📚",ar(monthDone("leap1")+monthDone("leap2")+monthDone("leap3")),"كتب LeapAhead",PURPLE),weight());metrics2.addView(metric("📖",ar(monthDone("quran1")+monthDone("quran2")),"جلسات قرآن",GREEN),weight());r.addView(metrics2);
        LinearLayout blocker=card();blocker.setPadding(dp(14),dp(12),dp(14),dp(12));add(r,blocker,10);blocker.addView(text("أكثر عائق مسجل",15,TEXT,true));blocker.addView(text(topBlocker(),16,RED,true));blocker.addView(text(blockerAdvice(),11,MUTED,false));blocker.setOnClickListener(v->startActivity(new Intent(this,WeeklyPlannerActivity.class)));return s;}

    private View rewardsScreen(){ScrollView s=scroll();LinearLayout r=root(s);topBar(r,"المكافآت","⋮","✦");int total=totalPoints();int level=levelIndex(total);int next=levelNext(level);int base=levelBase(level);
        LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setPadding(dp(17),dp(16),dp(17),dp(16));hero.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);hero.setBackground(round(NAVY,24));add(r,hero,10);LinearLayout hh=new LinearLayout(this);hh.setOrientation(LinearLayout.HORIZONTAL);hh.setGravity(Gravity.CENTER_VERTICAL);hh.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);LinearLayout htx=new LinearLayout(this);htx.setOrientation(LinearLayout.VERTICAL);htx.addView(text("إجمالي نقاط التقدم",12,Color.rgb(192,211,224),false));htx.addView(text(ar(total),31,WHITE,true));htx.addView(text("المستوى "+ar(level)+" • "+levelName(level),14,WHITE,true));hh.addView(htx,new LinearLayout.LayoutParams(0,-2,1));hh.addView(new BadgeView(this,GOLD,"★",70),new LinearLayout.LayoutParams(dp(74),dp(74)));hero.addView(hh);hero.addView(progress(Math.max(0,total-base),Math.max(1,next-base),GREEN2));TextView nh=text(level>=6?"وصلت إلى أعلى مستوى حالي":ar(Math.max(0,next-total))+" نقطة للمستوى التالي",11,Color.rgb(180,211,194),true);nh.setPadding(0,dp(5),0,0);hero.addView(nh);
        LinearLayout seg=segmented();String[][] rs={{"المستوى","level"},{"الأوسمة","badges"},{"الإنجازات","achievements"},{"المتجر","store"}};for(String[] x:rs){TextView b=segment(x[0],rewardTab.equals(x[1]));seg.addView(b,new LinearLayout.LayoutParams(0,dp(46),1));b.setOnClickListener(v->{rewardTab=x[1];render();});}add(r,seg,10);
        if(rewardTab.equals("badges"))badgesContent(r);else if(rewardTab.equals("achievements"))achievementsContent(r);else if(rewardTab.equals("store"))storeContent(r);else levelContent(r,total,level,next);return s;}

    private void levelContent(LinearLayout r,int total,int level,int next){LinearLayout c=card();c.setPadding(dp(15),dp(14),dp(15),dp(14));add(r,c,8);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.addView(new BadgeView(this,GREEN,ar(level),78),new LinearLayout.LayoutParams(dp(82),dp(82)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(12),0,0,0);tx.addView(text("المستوى الحالي",12,MUTED,false));tx.addView(text(levelName(level),24,NAVY,true));tx.addView(text(level>=6?"أعلى مستوى متاح حاليًا":"بقي "+ar(next-total)+" نقطة للمستوى التالي",11,MUTED,false));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));c.addView(row);section(r,"قوة المجالات","كل مجال يتطور منفصلًا");for(String d:new String[]{"القرآن","الإنجليزية والقبول","العمل والدخل","الصحة","المعرفة والقراءة"}){LinearLayout x=card();x.setPadding(dp(12),dp(10),dp(12),dp(10));add(r,x,5);int p=domainPoints(d);int tier=badgeTier(p);LinearLayout rr=new LinearLayout(this);rr.setOrientation(LinearLayout.HORIZONTAL);rr.setGravity(Gravity.CENTER_VERTICAL);rr.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);rr.addView(new BadgeView(this,color(d),tier==0?"·":ar(tier),50),new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout z=new LinearLayout(this);z.setOrientation(LinearLayout.VERTICAL);z.setPadding(dp(10),0,0,0);z.addView(text(shortDomain(d),14,TEXT,true));z.addView(text(badgeName(tier)+" • "+ar(p)+" نقطة",10,MUTED,false));z.addView(progress(p-badgeBase(tier),Math.max(1,badgeNext(tier)-badgeBase(tier)),color(d)));rr.addView(z,new LinearLayout.LayoutParams(0,-2,1));x.addView(rr);}}

    private void badgesContent(LinearLayout r){section(r,"الأوسمة","تُفتح بالنقاط داخل كل مجال");String[] ds={"القرآن","الإنجليزية والقبول","العمل والدخل","الصحة","المعرفة والقراءة","التواصل","الأسرة","الانضباط"};for(String d:ds){int p=domainPoints(d),tier=badgeTier(p);LinearLayout c=card();c.setPadding(dp(12),dp(11),dp(12),dp(11));add(r,c,6);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.addView(new BadgeView(this,color(d),domainIcon(d),62),new LinearLayout.LayoutParams(dp(68),dp(68)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(10),0,0,0);tx.addView(text(shortDomain(d),15,TEXT,true));tx.addView(text(badgeName(tier)+(tier<4?" • التالي عند "+ar(badgeNext(tier))+" نقطة":" • أعلى وسام"),11,MUTED,false));tx.addView(progress(p-badgeBase(tier),Math.max(1,badgeNext(tier)-badgeBase(tier)),color(d)));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));c.addView(row);}}

    private void achievementsContent(LinearLayout r){section(r,"إنجازات حقيقية","تُحسب من سجلك ولا تحتاج ضغط زر");achievement(r,"أسبوع ثابت","٥ أيام قوية خلال آخر ٧ أيام",strongLast7(),5,15,GREEN);achievement(r,"قارئ منتظم","٢٠ كتاب LeapAhead مكتمل",countDoneIds("leap"),20,15,PURPLE);achievement(r,"مراجعة راسخة","٢٠ جلسة قرآن مكتملة",countDoneIds("quran"),20,20,GREEN);achievement(r,"إنجليزية مستمرة","١٢ جلسة إنجليزية",countDoneIds("english"),12,15,BLUE);achievement(r,"عمل حقيقي","٨ جلسات عمل مكتملة",countDoneIds("work"),8,15,ORANGE);achievement(r,"جسم أقوى","٨ جلسات تمرين",countDoneIds("workout"),8,15,RED);}

    private void storeContent(LinearLayout r){LinearLayout wallet=card();wallet.setPadding(dp(14),dp(13),dp(14),dp(13));add(r,wallet,8);LinearLayout w=new LinearLayout(this);w.setOrientation(LinearLayout.HORIZONTAL);w.setGravity(Gravity.CENTER_VERTICAL);w.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);LinearLayout wt=new LinearLayout(this);wt.setOrientation(LinearLayout.VERTICAL);wt.addView(text("رصيد المكافآت",13,MUTED,true));wt.addView(text(ar(credits())+" رصيد",25,GREEN,true));w.addView(wt,new LinearLayout.LayoutParams(0,-2,1));w.addView(circle("✦",50,Color.rgb(235,248,240),GREEN,23));wallet.addView(w);wallet.addView(text("هذا الرصيد منفصل عن نقاط التقدم؛ إنفاقه لا ينقص مستواك.",11,MUTED,false));section(r,"مكافآت مناسبة","وقت إضافي فوق راحتك المعتادة — لا تشتري النوم أو الراحة الأساسية");rewardItem(r,"🎮","٣٠ دقيقة لعبة/أنمي إضافية","فوق وقت الترفيه اليومي المعتاد.",15,"fun30",PURPLE);rewardItem(r,"🧭","٤٥ دقيقة استكشاف حر","اختر موضوعًا تحبه دون شعور بالذنب.",20,"explore45",TEAL);rewardItem(r,"⚽","جلسة هواية إضافية","كرة، شطرنج، لعبة قصصية أو مهارة تحبها.",25,"hobby",GREEN);rewardItem(r,"🌙","مساء خفيف","ألغِ المهام الإضافية فقط في مساء واحد.",35,"light_evening",BLUE);rewardItem(r,"🎬","٩٠ دقيقة ترفيه ممتد","تستخدمها في يوم مناسب ولا تزاحم النوم أو المسجد.",45,"fun90",ORANGE);rewardItem(r,"🌿","نصف يوم مرن","تحتفظ بالأساسيات فقط: المسجد، القرآن، النوم؛ والباقي راحة/خروج.",70,"half_flex",GREEN);}

    private View moreScreen(){ScrollView s=scroll();LinearLayout r=root(s);topBar(r,"المزيد","⋮","⚙");LinearLayout profile=card();profile.setPadding(dp(15),dp(14),dp(15),dp(14));add(r,profile,10);profile.addView(text("مساري الشخصي",20,NAVY,true));profile.addView(text("نظامك السنوي للقرآن والإنجليزية والعمل والصحة والتعلم.",11,MUTED,false));addMenu(r,"▦","الأسبوع والتأجيل والعوائق","تقويم مرن + تسجيل أسباب التعثر",GREEN,()->startActivity(new Intent(this,WeeklyPlannerActivity.class)));addMenu(r,"✓","المراجعة والمهام المخصصة","مراجعة أسبوعية وشهرية + إضافة مهام",BLUE,()->startActivity(new Intent(this,PlannerCenterActivity.class)));addMenu(r,"♧","التذكيرات الذكية","قبل الإنجليزية والعمل والقرآن وإغلاق اليوم",GOLD,()->startActivity(new Intent(this,WeeklyPlannerActivity.class)));addMenu(r,"↥","النسخة الاحتياطية","تصدير واستعادة بيانات مساري",PURPLE,()->startActivity(new Intent(this,PlannerCenterActivity.class)));TextView v=center("مساري v0.10.0 • البيانات محفوظة محليًا",10,MUTED,false);v.setPadding(0,dp(18),0,dp(5));r.addView(v);return s;}

    private void syncRewardCredits(){Calendar now=Calendar.getInstance();String k=dateKey(now);int rate=dayRate(now);SharedPreferences.Editor e=prefs.edit();int c=credits();boolean changed=false;if(rate>=80&&!prefs.getBoolean("credit_day80_"+k,false)){c+=10;e.putBoolean("credit_day80_"+k,true);changed=true;}if(rate>=100&&!prefs.getBoolean("credit_day100_"+k,false)){c+=10;e.putBoolean("credit_day100_"+k,true);changed=true;}if(changed)e.putInt("reward_credits",c).apply();syncAchievement("ach_strong5",strongLast7()>=5,15);syncAchievement("ach_leap20",countDoneIds("leap")>=20,15);syncAchievement("ach_quran20",countDoneIds("quran")>=20,20);syncAchievement("ach_eng12",countDoneIds("english")>=12,15);syncAchievement("ach_work8",countDoneIds("work")>=8,15);syncAchievement("ach_workout8",countDoneIds("workout")>=8,15);}
    private void syncAchievement(String key,boolean unlocked,int reward){if(unlocked&&!prefs.getBoolean("credit_"+key,false)){prefs.edit().putBoolean("credit_"+key,true).putInt("reward_credits",credits()+reward).apply();}}
    private int credits(){return prefs.getInt("reward_credits",0);}
    private void rewardItem(LinearLayout r,String icon,String title,String desc,int cost,String id,int c){LinearLayout x=card();x.setPadding(dp(12),dp(11),dp(12),dp(11));add(r,x,6);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.addView(circle(icon,48,soft(c),c,20));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(10),0,dp(8),0);tx.addView(text(title,14,TEXT,true));tx.addView(text(desc,10,MUTED,false));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));Button b=button(ar(cost)+" رصيد",c);row.addView(b,new LinearLayout.LayoutParams(dp(94),dp(42)));x.addView(row);b.setOnClickListener(v->redeem(title,cost,id));}
    private void redeem(String title,int cost,String id){if(credits()<cost){Toast.makeText(this,"رصيد المكافآت غير كافٍ",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("استخدام المكافأة؟").setMessage(title+"\n\nسيتم خصم "+ar(cost)+" من رصيد المكافآت، ولن تنقص نقاط تقدمك.").setPositiveButton("استخدام",(d,w)->{prefs.edit().putInt("reward_credits",credits()-cost).putLong("redeem_"+id+"_"+System.currentTimeMillis(),System.currentTimeMillis()).apply();Toast.makeText(this,"استمتع بالمكافأة 🌟",Toast.LENGTH_LONG).show();render();}).setNegativeButton("إلغاء",null).show();}

    private void achievement(LinearLayout r,String title,String desc,int value,int target,int reward,int c){boolean open=value>=target;LinearLayout x=card();x.setPadding(dp(12),dp(10),dp(12),dp(10));if(!open)x.setAlpha(.62f);add(r,x,5);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.addView(new BadgeView(this,open?c:Color.rgb(150,156,165),open?"✓":"·",50),new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(10),0,0,0);tx.addView(text(title,14,open?TEXT:MUTED,true));tx.addView(text(desc,10,MUTED,false));tx.addView(progress(Math.min(value,target),target,open?c:MUTED));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView rw=pill(open?"+"+ar(reward)+" رصيد":ar(Math.min(value,target))+"/"+ar(target),open?GREEN:MUTED,Color.rgb(247,249,252));row.addView(rw);x.addView(row);}

    private List<T> tasksToday(){return tasksFor(Calendar.getInstance());}
    private List<T> tasksFor(Calendar d){List<T>a=new ArrayList<>();int day=d.get(Calendar.DAY_OF_WEEK);a.add(t("fajr",240,390,"الفجر • المسجد • الحلقة • الدرس","الدين والمسجد",8,true,"☾"));if(day==Calendar.SATURDAY)a.add(t("workoutA",390,420,"تمرين A — كتف وذراعان + جسم كامل","الصحة",18,true,"♥"));else if(day==Calendar.TUESDAY)a.add(t("workoutB",390,420,"تمرين B — أوتار وقبضة وسرعة","الصحة",18,true,"♥"));a.add(t("english",420,480,englishTitle(day),"الإنجليزية والقبول",day==Calendar.FRIDAY?10:24,day!=Calendar.FRIDAY,"🎧"));a.add(t("sleep2",480,570,"نوم تكميلي","الصحة",8,true,"☁"));a.add(t("leap1",570,600,"LeapAhead — الكتاب ١","المعرفة والقراءة",8,true,"📚"));a.add(t("work",600,690,workTitle(day),"العمل والدخل",day==Calendar.FRIDAY?10:30,day!=Calendar.FRIDAY,"▣"));a.add(t("quran1",705,780,"القرآن — مراجعة جديدة: صفحتان","القرآن",18,true,"📖"));a.add(t("lunch",780,810,"الغداء","الانضباط",0,false,"☕"));a.add(t("leap2",810,855,"LeapAhead — الكتاب ٢","المعرفة والقراءة",8,true,"📚"));a.add(t("quran2",885,970,"القرآن — صفحتان + مراجعة قديمة واختبار بصري","القرآن",22,true,"📖"));a.add(afternoon(day));a.add(t("maghrib",1080,1200,"المغرب • التحفيظ • العشاء","الدين والمسجد",8,true,"☾"));a.add(t("leap3",1230,1275,"LeapAhead — الكتاب ٣ (إضافي)","المعرفة والقراءة",8,false,"📚"));a.add(t("close",1320,1340,"إغلاق اليوم وتحديد الغد","الانضباط",6,true,"✓"));a.add(t("sleep",1340,1350,"إبعاد الهاتف والاستعداد للنوم","الصحة",6,true,"☁"));addCustom(a,d);return a;}
    private T afternoon(int d){switch(d){case Calendar.SATURDAY:return t("family_talk",990,1020,"وقت الأسرة + ١٠ دقائق تدريب كلام","الأسرة",10,true,"👥");case Calendar.SUNDAY:return t("talk1",990,1020,"تدريب التواصل ١٠ دقائق + محادثة واحدة","التواصل",10,true,"◉");case Calendar.MONDAY:return t("family_friend",990,1020,"خدمة الأسرة + تفقد صديق","الأسرة",10,true,"👥");case Calendar.TUESDAY:return t("talk2",990,1020,"تدريب الحزم وتنظيم الكلام","التواصل",10,true,"◉");case Calendar.WEDNESDAY:return t("medicine",990,1050,"مراجعة طب قديم ٤٥–٦٠ دقيقة","المعرفة والقراءة",14,true,"⚕");case Calendar.THURSDAY:return t("khatera",990,1030,"خاطرة دينية + تدريب إلقاء","التواصل",12,true,"◉");default:return t("explore",990,1050,"استكشاف علمي أو مهارة حياة","المعرفة والقراءة",10,false,"✦");}}
    private void addCustom(List<T>a,Calendar d){try{JSONArray arr=new JSONArray(prefs.getString("custom_tasks","[]"));for(int i=0;i<arr.length();i++){JSONObject o=arr.optJSONObject(i);if(o==null||!o.optBoolean("active",true))continue;int day=o.optInt("day",0);if(day!=0&&day!=d.get(Calendar.DAY_OF_WEEK))continue;a.add(t(o.optString("id","custom_"+i),o.optInt("start",960),o.optInt("end",990),o.optString("title","مهمة مخصصة"),o.optString("domain","الانضباط"),o.optInt("points",10),o.optBoolean("required",false),"✦"));}}catch(Exception ignored){}}
    private T t(String i,int s,int e,String x,String d,int p,boolean r,String icon){return new T(i,s,e,x,d,p,r,icon);}
    private String englishTitle(int d){switch(d){case Calendar.SATURDAY:return"الإنجليزية: مفردات + Reading Explorer";case Calendar.SUNDAY:return"الإنجليزية: مفردات + Tactics for Listening";case Calendar.MONDAY:return"الإنجليزية: مفردات + Reading Explorer";case Calendar.TUESDAY:return"الإنجليزية: مفردات + Tactics for Listening";case Calendar.WEDNESDAY:return"الإنجليزية: مفردات + Oxford Bookworms";case Calendar.THURSDAY:return"اختبار الإنجليزية الأسبوعي";default:return"استماع إنجليزي ممتع — يوم خفيف";}}
    private String workTitle(int d){switch(d){case Calendar.SATURDAY:case Calendar.SUNDAY:return"العمل: تطوير الأكاديمية — إنجاز جزء قابل للاختبار";case Calendar.MONDAY:case Calendar.TUESDAY:return"العمل: الوصول للسوق — عرض/تواصل/اختبار طلب";case Calendar.WEDNESDAY:return"العمل: دخل مباشر — خدمة أو طالب محتمل";case Calendar.THURSDAY:return"العمل: مراجعة الأرقام والنتائج";default:return"مراجعة مالية خفيفة";}}

    private boolean done(T t){return prefs.getBoolean("reward_done_"+todayKey+"_"+t.id,false);}private void setDone(T t,boolean v){boolean old=done(t);if(old==v)return;int delta=v?t.points:-t.points;String dk="reward_day_points_"+todayKey,dom="reward_domain_"+t.domain;SharedPreferences.Editor e=prefs.edit().putBoolean("reward_done_"+todayKey+"_"+t.id,v);if(t.points>0)e.putInt(dk,Math.max(0,prefs.getInt(dk,0)+delta)).putInt(dom,Math.max(0,prefs.getInt(dom,0)+delta));e.apply();syncRewardCredits();Toast.makeText(this,v?"+"+t.points+" نقطة تقدم":"تم إلغاء الإنجاز",Toast.LENGTH_SHORT).show();}
    private int dayPoints(Calendar c){return prefs.getInt("reward_day_points_"+dateKey(c),0);}private int dayTarget(Calendar c){int n=0;for(T t:tasksFor(c))if(t.required)n+=t.points;return Math.max(1,n);}private int dayRate(Calendar c){return pct(dayPoints(c),dayTarget(c));}
    private int weekRate(){Calendar c=saturdayStart(Calendar.getInstance());int p=0,t=0;for(int i=0;i<7;i++){p+=dayPoints(c);t+=dayTarget(c);c.add(Calendar.DAY_OF_MONTH,1);}return pct(p,t);}private int monthRate(){Calendar c=Calendar.getInstance();c.set(Calendar.DAY_OF_MONTH,1);int m=c.get(Calendar.MONTH),p=0,t=0;while(c.get(Calendar.MONTH)==m){p+=dayPoints(c);t+=dayTarget(c);c.add(Calendar.DAY_OF_MONTH,1);}return pct(p,t);}private int yearRate(){Calendar start=Calendar.getInstance();start.set(2026,Calendar.SEPTEMBER,1,0,0,0);Calendar end=Calendar.getInstance();end.set(2027,Calendar.MAY,31,23,59,59);Calendar now=Calendar.getInstance();if(now.before(start))return 0;Calendar c=(Calendar)start.clone();int p=0,t=0;while(!c.after(now)&&!c.after(end)){p+=dayPoints(c);t+=dayTarget(c);c.add(Calendar.DAY_OF_MONTH,1);}return pct(p,t);}
    private int totalPoints(){int n=0;for(String d:domainColors.keySet())n+=domainPoints(d);return n;}private int domainPoints(String d){return prefs.getInt("reward_domain_"+d,0);}private int countDoneToday(){int n=0;for(T t:tasksToday())if(done(t))n++;return n;}
    private int monthDone(String id){Calendar c=Calendar.getInstance();c.set(Calendar.DAY_OF_MONTH,1);int m=c.get(Calendar.MONTH),n=0;while(c.get(Calendar.MONTH)==m){if(prefs.getBoolean("reward_done_"+dateKey(c)+"_"+id,false))n++;c.add(Calendar.DAY_OF_MONTH,1);}return n;}private int monthCompleted(){Calendar c=Calendar.getInstance();c.set(Calendar.DAY_OF_MONTH,1);int m=c.get(Calendar.MONTH),n=0;while(c.get(Calendar.MONTH)==m){String k=dateKey(c);for(T t:tasksFor(c))if(prefs.getBoolean("reward_done_"+k+"_"+t.id,false))n++;c.add(Calendar.DAY_OF_MONTH,1);}return n;}private int monthPlanned(){Calendar c=Calendar.getInstance();c.set(Calendar.DAY_OF_MONTH,1);int m=c.get(Calendar.MONTH),n=0;while(c.get(Calendar.MONTH)==m){n+=tasksFor(c).size();c.add(Calendar.DAY_OF_MONTH,1);}return n;}private int monthStrongDays(){Calendar c=Calendar.getInstance();c.set(Calendar.DAY_OF_MONTH,1);int m=c.get(Calendar.MONTH),n=0;while(c.get(Calendar.MONTH)==m){if(dayRate(c)>=80)n++;c.add(Calendar.DAY_OF_MONTH,1);}return n;}
    private int focusMinutes(){Calendar c=Calendar.getInstance();c.set(Calendar.DAY_OF_MONTH,1);int m=c.get(Calendar.MONTH),sum=0;while(c.get(Calendar.MONTH)==m){String k=dateKey(c);for(T t:tasksFor(c))if(prefs.getBoolean("reward_done_"+k+"_"+t.id,false)&&(t.domain.equals("الإنجليزية والقبول")||t.domain.equals("العمل والدخل")||t.domain.equals("القرآن")||t.domain.equals("المعرفة والقراءة")))sum+=Math.max(0,t.end-t.start);c.add(Calendar.DAY_OF_MONTH,1);}return sum;}private String formatHours(int min){return ar(min/60)+":"+(min%60<10?"٠":"")+ar(min%60)+" س";}
    private int countDoneIds(String contains){int n=0;for(Map.Entry<String,?> e:prefs.getAll().entrySet())if(e.getKey().startsWith("reward_done_")&&e.getKey().contains("_"+contains)&&Boolean.TRUE.equals(e.getValue()))n++;return n;}private int strongLast7(){Calendar c=Calendar.getInstance();c.add(Calendar.DAY_OF_MONTH,-6);int n=0;for(int i=0;i<7;i++){if(dayRate(c)>=80)n++;c.add(Calendar.DAY_OF_MONTH,1);}return n;}
    private int streak(){Calendar c=Calendar.getInstance();if(dayRate(c)<80)c.add(Calendar.DAY_OF_MONTH,-1);int n=0;for(int i=0;i<365;i++){if(dayRate(c)>=80){n++;c.add(Calendar.DAY_OF_MONTH,-1);}else break;}return n;}private String flames(int n){if(n<=0)return"○ ○ ○";StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(7,n);i++)b.append("● ");return b.toString();}

    private int levelIndex(int p){if(p>=8000)return 6;if(p>=5000)return 5;if(p>=3000)return 4;if(p>=1500)return 3;if(p>=600)return 2;return 1;}private int levelBase(int l){switch(l){case 2:return600;case 3:return1500;case 4:return3000;case 5:return5000;case 6:return8000;default:return0;}}private int levelNext(int l){switch(l){case 1:return600;case 2:return1500;case 3:return3000;case 4:return5000;case 5:return8000;default:return8000;}}private String levelName(int l){switch(l){case 2:return"منطلق";case 3:return"ثابت";case 4:return"متقدم";case 5:return"متمكن";case 6:return"راسخ";default:return"البداية";}}
    private int badgeTier(int p){if(p>=1200)return 4;if(p>=700)return 3;if(p>=350)return 2;if(p>=120)return 1;return 0;}private int badgeBase(int t){switch(t){case 1:return120;case 2:return350;case 3:return700;case 4:return1200;default:return0;}}private int badgeNext(int t){switch(t){case 0:return120;case 1:return350;case 2:return700;case 3:return1200;default:return1200;}}private String badgeName(int t){switch(t){case 1:return"برونزي";case 2:return"فضي";case 3:return"ذهبي";case 4:return"متمكن";default:return"لم يُفتح بعد";}}

    private String topBlocker(){try{JSONArray a=new JSONArray(prefs.getString("task_state_events","[]"));LinkedHashMap<String,Integer> m=new LinkedHashMap<>();Calendar lim=Calendar.getInstance();lim.add(Calendar.DAY_OF_MONTH,-30);String limKey=dateKey(lim);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null||"تم".equals(o.optString("status"))||o.optString("date").compareTo(limKey)<0)continue;String x=o.optString("reason");if(x.isEmpty()||x.equals("—"))continue;m.put(x,m.containsKey(x)?m.get(x)+1:1);}String top="لا توجد بيانات كافية بعد";int max=0;for(String x:m.keySet())if(m.get(x)>max){max=m.get(x);top=x;}return top;}catch(Exception e){return"لا توجد بيانات كافية بعد";}}private String blockerAdvice(){String x=topBlocker();if(x.contains("فكرة"))return"اكتب الفكرة في «لاحقًا» خلال ٢٠ ثانية ثم ارجع للمهمة.";if(x.contains("يوتيوب")||x.contains("تصفح"))return"افتح الهاتف بهدف واحد وحدد مؤقتًا قبل بدء التصفح.";if(x.contains("نوم")||x.contains("تعب"))return"راجع وقت النوم أولًا؛ لا تعالج الإرهاق بمزيد من الضغط.";if(x.contains("وقت"))return"صغّر المهمة إلى نسخة ١٠ دقائق بدل إسقاطها بالكامل.";return"سجّل التأجيل والتعثر باستمرار ليظهر النمط الحقيقي واقتراح أدق.";}

    private boolean matches(T t){if(taskFilter.equals("الكل"))return true;if(taskFilter.equals("قرآن"))return t.domain.equals("القرآن");if(taskFilter.equals("إنجليزية"))return t.domain.equals("الإنجليزية والقبول");if(taskFilter.equals("عمل"))return t.domain.equals("العمل والدخل");if(taskFilter.equals("صحة"))return t.domain.equals("الصحة");if(taskFilter.equals("قراءة"))return t.domain.equals("المعرفة والقراءة");if(taskFilter.equals("أسرة"))return t.domain.equals("الأسرة");return true;}
    private String homeMessage(){int p=dayRate(Calendar.getInstance());return p>=100?"أنهيت هدف اليوم. حافظ على النوم والهدوء.":p>=80?"يوم قوي حتى الآن — لا تفسده بالمبالغة.":p>=40?"تقدمت جيدًا؛ أكمل أهم مهمة تالية.":"ابدأ بأول مهمة واضحة أمامك.";}
    private String shortDomain(String d){if(d.equals("الإنجليزية والقبول"))return"الإنجليزية";if(d.equals("العمل والدخل"))return"العمل";if(d.equals("المعرفة والقراءة"))return"المعرفة";if(d.equals("الدين والمسجد"))return"المسجد";return d;}private String domainIcon(String d){if(d.equals("القرآن"))return"ق";if(d.equals("الإنجليزية والقبول"))return"E";if(d.equals("العمل والدخل"))return"▣";if(d.equals("الصحة"))return"♥";if(d.equals("المعرفة والقراءة"))return"✦";if(d.equals("التواصل"))return"◉";if(d.equals("الأسرة"))return"⌂";return"✓";}
    private int color(String d){Integer c=domainColors.get(d);return c==null?GREEN:c;}private int soft(int c){return Color.rgb((Color.red(c)+255*5)/6,(Color.green(c)+255*5)/6,(Color.blue(c)+255*5)/6);}

    private LinearLayout bottomNav(){LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.HORIZONTAL);n.setGravity(Gravity.CENTER);n.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);n.setPadding(dp(5),dp(6),dp(5),dp(6));n.setBackgroundColor(NAVY);nav(n,"⌂","الرئيسية","home");nav(n,"☑","المهام","tasks");nav(n,"▥","الإحصائيات","stats");nav(n,"♛","المكافآت","rewards");nav(n,"•••","المزيد","more");return n;}private void nav(LinearLayout n,String icon,String label,String key){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);if(tab.equals(key))x.setBackground(round(GREEN,16));x.addView(center(icon,20,WHITE,true));x.addView(center(label,10,WHITE,tab.equals(key)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);lp.setMargins(dp(2),0,dp(2),0);n.addView(x,lp);x.setOnClickListener(v->{tab=key;render();});}
    private void topBar(LinearLayout r,String title,String left,String right){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.addView(center(right,20,NAVY,true),new LinearLayout.LayoutParams(dp(44),dp(44)));row.addView(center(title,24,title.equals("مساري")?GREEN:TEXT,true),new LinearLayout.LayoutParams(0,dp(44),1));row.addView(center(left,20,NAVY,true),new LinearLayout.LayoutParams(dp(44),dp(44)));r.addView(row);}private void section(LinearLayout r,String title,String sub){LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.HORIZONTAL);h.setGravity(Gravity.CENTER_VERTICAL);h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);h.setPadding(0,dp(16),0,dp(5));h.addView(text(title,17,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));if(!sub.isEmpty())h.addView(text(sub,10,MUTED,false));r.addView(h);}
    private void miniRing(LinearLayout p,String label,int pct,int c){LinearLayout w=new LinearLayout(this);w.setOrientation(LinearLayout.VERTICAL);w.setGravity(Gravity.CENTER);w.addView(new Ring(this,pct,c),new LinearLayout.LayoutParams(dp(67),dp(67)));w.addView(center(label,10,MUTED,false));p.addView(w,new LinearLayout.LayoutParams(0,dp(90),1));}
    private void compactTask(LinearLayout r,T t){LinearLayout c=card();c.setPadding(dp(10),dp(8),dp(10),dp(8));add(r,c,5);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);CheckBox cb=new CheckBox(this);cb.setChecked(done(t));cb.setButtonTintList(ColorStateList.valueOf(color(t.domain)));row.addView(cb,new LinearLayout.LayoutParams(dp(42),dp(45)));row.addView(circle(t.icon,38,soft(color(t.domain)),color(t.domain),16));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(9),0,dp(9),0);tx.addView(text(t.title,13,TEXT,true));tx.addView(text(time(t.start)+" • "+shortDomain(t.domain),10,MUTED,false));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));c.addView(row);cb.setOnCheckedChangeListener((v,ch)->{setDone(t,ch);render();});}
    private void fullTask(LinearLayout r,T t){LinearLayout c=card();c.setPadding(dp(11),dp(9),dp(11),dp(9));add(r,c,6);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);CheckBox cb=new CheckBox(this);cb.setChecked(done(t));cb.setButtonTintList(ColorStateList.valueOf(color(t.domain)));row.addView(cb,new LinearLayout.LayoutParams(dp(44),dp(52)));row.addView(circle(t.icon,42,soft(color(t.domain)),color(t.domain),17));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(9),0,dp(9),0);tx.addView(text(t.title,14,TEXT,true));tx.addView(text(time(t.start)+" — "+time(t.end)+" • "+shortDomain(t.domain),10,MUTED,false));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));if(t.points>0)row.addView(pill("+"+ar(t.points),color(t.domain),soft(color(t.domain))));c.addView(row);cb.setOnCheckedChangeListener((v,ch)->{setDone(t,ch);render();});}
    private void weekStrip(LinearLayout r){Calendar start=saturdayStart(Calendar.getInstance());LinearLayout strip=new LinearLayout(this);strip.setOrientation(LinearLayout.HORIZONTAL);strip.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);for(int i=0;i<7;i++){Calendar d=(Calendar)start.clone();d.add(Calendar.DAY_OF_MONTH,i);boolean now=dateKey(d).equals(todayKey);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);x.setPadding(dp(4),dp(5),dp(4),dp(5));if(now)x.setBackground(round(GREEN,14));x.addView(center(new SimpleDateFormat("EEE",new Locale("ar")).format(d.getTime()).replace("،",""),9,now?WHITE:MUTED,false));x.addView(center(ar(d.get(Calendar.DAY_OF_MONTH)),13,now?WHITE:TEXT,true));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(57),1);lp.setMargins(dp(2),0,dp(2),0);strip.addView(x,lp);}add(r,strip,10);}
    private TextView chip(String s,boolean active){int c=filterColor(s);TextView t=center(s,11,active?WHITE:c,true);t.setPadding(dp(13),dp(7),dp(13),dp(7));t.setBackground(round(active?c:soft(c),15));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(35));lp.setMargins(dp(3),0,dp(3),0);t.setLayoutParams(lp);return t;}private int filterColor(String s){if(s.equals("قرآن"))return GREEN;if(s.equals("إنجليزية"))return BLUE;if(s.equals("عمل"))return ORANGE;if(s.equals("صحة"))return RED;if(s.equals("قراءة"))return PURPLE;if(s.equals("أسرة"))return PINK;return GREEN;}
    private LinearLayout segmented(){LinearLayout s=new LinearLayout(this);s.setOrientation(LinearLayout.HORIZONTAL);s.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);s.setPadding(dp(3),dp(3),dp(3),dp(3));s.setBackground(round(WHITE,18,BORDER));return s;}private TextView segment(String s,boolean active){TextView t=center(s,11,active?WHITE:NAVY,true);if(active)t.setBackground(round(GREEN,15));return t;}
    private View quick(String icon,String label,int c){LinearLayout x=card();x.setGravity(Gravity.CENTER);x.setPadding(dp(4),dp(9),dp(4),dp(9));x.addView(circle(icon,38,soft(c),c,16));x.addView(center(label,10,TEXT,true));return x;}
    private View bigRing(int pct,String label,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);x.addView(new Ring(this,pct,c),new LinearLayout.LayoutParams(dp(102),dp(102)));x.addView(center(label,11,MUTED,true));return x;}private View stat(String value,String label,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(8),dp(5),dp(8),dp(5));x.addView(text(value,18,c,true));x.addView(text(label,10,MUTED,false));return x;}private View metric(String icon,String value,String label,int c){LinearLayout x=card();x.setGravity(Gravity.CENTER);x.setPadding(dp(6),dp(10),dp(6),dp(10));x.addView(center(icon,18,c,true));x.addView(center(value,15,TEXT,true));x.addView(center(label,9,MUTED,false));return x;}
    private void domainRow(LinearLayout p,String d){int pts=domainPoints(d),tier=badgeTier(pts);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(0,dp(5),0,dp(5));LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.HORIZONTAL);h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);h.addView(text(shortDomain(d),12,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));h.addView(text(ar(pts)+" • "+badgeName(tier),10,color(d),true));row.addView(h);row.addView(progress(pts-badgeBase(tier),Math.max(1,badgeNext(tier)-badgeBase(tier)),color(d)));p.addView(row);}
    private void addMenu(LinearLayout r,String icon,String title,String sub,int c,Runnable run){LinearLayout x=card();x.setPadding(dp(12),dp(11),dp(12),dp(11));add(r,x,7);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.addView(circle(icon,44,soft(c),c,18));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(10),0,dp(10),0);tx.addView(text(title,14,TEXT,true));tx.addView(text(sub,10,MUTED,false));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));row.addView(text("‹",23,MUTED,false));x.addView(row);x.setOnClickListener(v->run.run());}

    private ScrollView scroll(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(BG);s.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return s;}private LinearLayout root(ScrollView s){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(15),dp(16),dp(28));r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);s.addView(r);return r;}private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);c.setBackground(round(WHITE,19,BORDER));c.setElevation(dp(1));return c;}private void add(LinearLayout r,View v,int top){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(top),0,0);r.addView(v,lp);}private TextView text(String s,int size,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(c);t.setGravity(Gravity.RIGHT);t.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private TextView center(String s,int size,int c,boolean bold){TextView t=text(s,size,c,bold);t.setGravity(Gravity.CENTER);return t;}private TextView pill(String s,int c,int bg){TextView t=center(s,10,c,true);t.setPadding(dp(8),dp(4),dp(8),dp(4));t.setBackground(round(bg,18));return t;}private Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(WHITE);b.setTextSize(11);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(round(c,14));return b;}private TextView circle(String s,int size,int bg,int fg,int textSize){TextView t=center(s,textSize,fg,true);t.setBackground(round(bg,999));t.setPadding(0,0,0,0);t.setLayoutParams(new LinearLayout.LayoutParams(dp(size),dp(size)));return t;}private ProgressBar progress(int val,int max,int c){ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(Math.max(1,max));p.setProgress(Math.max(0,Math.min(val,Math.max(1,max))));p.setProgressTintList(ColorStateList.valueOf(c));p.setProgressBackgroundTintList(ColorStateList.valueOf(Color.rgb(230,235,241)));p.setMinimumHeight(dp(6));return p;}private LinearLayout.LayoutParams weight(){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(3),0,dp(3),0);return lp;}private GradientDrawable round(int c,int rad){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(rad));return d;}private GradientDrawable round(int c,int rad,int stroke){GradientDrawable d=round(c,rad);d.setStroke(dp(1),stroke);return d;}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private int pct(int v,int t){return t<=0?0:Math.max(0,Math.min(100,Math.round(v*100f/t)));}private String ar(int n){return String.valueOf(n).replace('0','٠').replace('1','١').replace('2','٢').replace('3','٣').replace('4','٤').replace('5','٥').replace('6','٦').replace('7','٧').replace('8','٨').replace('9','٩');}private String dateKey(Calendar c){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(c.getTime());}private Calendar saturdayStart(Calendar c){Calendar x=(Calendar)c.clone();int diff=(x.get(Calendar.DAY_OF_WEEK)-Calendar.SATURDAY+7)%7;x.add(Calendar.DAY_OF_MONTH,-diff);return x;}private String time(int m){int h=(m/60)%24,mi=m%60;String ap=h<12?"ص":"م";int hh=h%12;if(hh==0)hh=12;return ar(hh)+":"+(mi<10?"٠":"")+ar(mi)+" "+ap;}

    class Ring extends View {Paint p=new Paint(1);int val,c;Ring(Activity a,int v,int color){super(a);val=v;c=color;}protected void onDraw(Canvas x){super.onDraw(x);float sw=dp(7),pad=sw+dp(2);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(sw);p.setStrokeCap(Paint.Cap.ROUND);p.setColor(Color.rgb(232,236,242));x.drawArc(new RectF(pad,pad,getWidth()-pad,getHeight()-pad),-90,360,false,p);p.setColor(c);x.drawArc(new RectF(pad,pad,getWidth()-pad,getHeight()-pad),-90,360*val/100f,false,p);p.setStyle(Paint.Style.FILL);p.setColor(TEXT);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(17));x.drawText(ar(val)+"٪",getWidth()/2f,getHeight()/2f+dp(6),p);}}
    class BadgeView extends View {Paint p=new Paint(1);int c;String label;BadgeView(Activity a,int color,String s,int ignored){super(a);c=color;label=s;}protected void onDraw(Canvas x){super.onDraw(x);float w=getWidth(),h=getHeight(),cx=w/2f,cy=h/2f,r=Math.min(w,h)*.43f;Path q=new Path();for(int i=0;i<6;i++){double a=Math.toRadians(-90+i*60);float px=cx+(float)Math.cos(a)*r,py=cy+(float)Math.sin(a)*r;if(i==0)q.moveTo(px,py);else q.lineTo(px,py);}q.close();p.setStyle(Paint.Style.FILL);p.setColor(soft(c));x.drawPath(q,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(3));p.setColor(c);x.drawPath(q,p);p.setStyle(Paint.Style.FILL);p.setColor(c);x.drawCircle(cx,cy,r*.62f,p);p.setColor(WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(Math.min(w,h)*.25f);x.drawText(label,cx,cy+p.getTextSize()*.35f,p);}}
    class WeekBars extends View {Paint p=new Paint(1);WeekBars(Activity a){super(a);}protected void onDraw(Canvas x){super.onDraw(x);float left=dp(12),bottom=getHeight()-dp(28),top=dp(16),gap=dp(8),bw=(getWidth()-left*2-gap*5)/6f;Calendar c=saturdayStart(Calendar.getInstance());c.add(Calendar.DAY_OF_MONTH,-35);for(int i=0;i<6;i++){int po=0,ta=0;Calendar w=(Calendar)c.clone();for(int j=0;j<7;j++){po+=dayPoints(w);ta+=dayTarget(w);w.add(Calendar.DAY_OF_MONTH,1);}int v=pct(po,ta);float h=(bottom-top)*v/100f,l=left+i*(bw+gap);p.setColor(i==5?GREEN:Color.rgb(220,226,234));x.drawRoundRect(new RectF(l,bottom-h,l+bw,bottom),dp(5),dp(5),p);p.setColor(MUTED);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(dp(9));x.drawText(ar(v)+"٪",l+bw/2,bottom-h-dp(5),p);x.drawText("أ"+ar(i+1),l+bw/2,getHeight()-dp(8),p);c.add(Calendar.DAY_OF_MONTH,7);}}}
    class Trend extends View {Paint p=new Paint(1);Path path=new Path();Trend(Activity a){super(a);}protected void onDraw(Canvas x){super.onDraw(x);float l=dp(12),r=getWidth()-dp(12),t=dp(18),b=getHeight()-dp(22);p.setStrokeWidth(dp(1));p.setColor(Color.rgb(232,236,241));for(int i=0;i<4;i++){float y=t+(b-t)*i/3f;x.drawLine(l,y,r,y,p);}Calendar c=Calendar.getInstance();c.add(Calendar.DAY_OF_MONTH,-29);path.reset();for(int i=0;i<30;i++){float xx=l+(r-l)*i/29f,yy=b-(b-t)*dayRate(c)/100f;if(i==0)path.moveTo(xx,yy);else path.lineTo(xx,yy);c.add(Calendar.DAY_OF_MONTH,1);}p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(3));p.setStrokeCap(Paint.Cap.ROUND);p.setStrokeJoin(Paint.Join.ROUND);p.setColor(GREEN);x.drawPath(path,p);p.setStyle(Paint.Style.FILL);}}
}
