package com.masari.personalplan;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public class TaskDetailV19Activity extends Activity {
    private static final int GREEN=Color.rgb(20,145,80), NAVY=Color.rgb(7,42,61), BLUE=Color.rgb(67,130,213), ORANGE=Color.rgb(235,145,49), PURPLE=Color.rgb(133,84,190);
    private SharedPreferences p;
    private String id,title,domain;
    private int points;
    private int BG,CARD,TEXT,MUTED,BORDER;

    @Override protected void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("masari_data",MODE_PRIVATE);id=getIntent().getStringExtra("task_id");title=getIntent().getStringExtra("task_title");domain=getIntent().getStringExtra("task_domain");points=getIntent().getIntExtra("task_points",10);if(title==null)title=id==null?"سجل المهمات":"المهمة";if(domain==null)domain="عام";palette();render();}
    @Override protected void onResume(){super.onResume();if(p!=null){palette();render();}}

    private void palette(){boolean dark=p.getBoolean("dark_mode",false);BG=dark?Color.rgb(17,24,29):Color.rgb(249,250,251);CARD=dark?Color.rgb(27,36,42):Color.WHITE;TEXT=dark?Color.rgb(239,244,246):Color.rgb(24,31,39);MUTED=dark?Color.rgb(164,178,186):Color.rgb(107,116,126);BORDER=dark?Color.rgb(47,60,68):Color.rgb(231,234,237);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(NAVY);}

    private void render(){ScrollView s=new ScrollView(this);s.setBackgroundColor(BG);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.setPadding(dp(14),dp(8),dp(14),dp(24));s.addView(r);LinearLayout top=row();TextView back=tv("‹",25,TEXT,true);back.setGravity(Gravity.CENTER);top.addView(back,new LinearLayout.LayoutParams(dp(44),dp(44)));TextView h=tv(id==null?"سجل المهمات":title,19,TEXT,true);h.setGravity(Gravity.CENTER);top.addView(h,new LinearLayout.LayoutParams(0,dp(44),1));TextView more=tv("•••",17,TEXT,true);more.setGravity(Gravity.CENTER);top.addView(more,new LinearLayout.LayoutParams(dp(44),dp(44)));r.addView(top);back.setOnClickListener(v->finish());more.setOnClickListener(v->{if(id!=null)showEditor();});if(id==null)renderGeneral(r);else renderTask(r);setContentView(s);}

    private void renderTask(LinearLayout r){LinearLayout hero=card();hero.setPadding(dp(13),dp(12),dp(13),dp(12));add(r,hero,10);hero.addView(tv(domain,10,GREEN,true));hero.addView(tv(scheduleSummary(),12,TEXT,true));hero.addView(tv("اضغط «تعديل الجدولة» لتغيير الوقت أو الأيام أو جعله شهريًا.",9,MUTED,false));
        LinearLayout stats=row();stats.setPadding(0,dp(10),0,0);stats.addView(metric(ar(done30()),"مكتملة 30 يوم",GREEN),weight());stats.addView(metric(ar(partial30()),"جزئية",ORANGE),weight());stats.addView(metric(formatMinutes(focus30()),"تركيز فعلي",BLUE),weight());hero.addView(stats);

        addHeader(r,"حالة اليوم","تدخل مباشرة في إحصائيات الشهر");LinearLayout status=card();status.setPadding(dp(9),dp(9),dp(9),dp(9));add(r,status,5);LinearLayout a=row();Button done=button("مكتملة",GREEN),partial=button("جزئية",ORANGE);a.addView(done,weightButton());a.addView(partial,weightButton());status.addView(a);LinearLayout b=row();Button cancel=button("إلغاء مقبول",Color.rgb(102,113,126)),reset=button("إعادة ضبط",NAVY);b.addView(cancel,weightButton());b.addView(reset,weightButton());status.addView(b);TextView current=tv("الحالة الآن: "+statusLabel(todayStatus()),9,MUTED,true);current.setPadding(0,dp(7),0,0);status.addView(current);done.setOnClickListener(v->setTodayStatus("done"));partial.setOnClickListener(v->setTodayStatus("partial"));cancel.setOnClickListener(v->setTodayStatus("cancelled"));reset.setOnClickListener(v->setTodayStatus("none"));

        addHeader(r,"ملاحظة اليوم","سجّل ما يفيدك لاحقًا، لا يوميات طويلة");LinearLayout note=card();note.setPadding(dp(10),dp(9),dp(10),dp(9));add(r,note,5);EditText e=input("ماذا أنجزت؟ أين تعثرت؟ ما الذي أريد تذكره؟");e.setMinLines(3);e.setText(p.getString(noteKey(today()),""));note.addView(e);Button save=button("حفظ الملاحظة",PURPLE);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(46));sp.setMargins(0,dp(8),0,0);note.addView(save,sp);save.setOnClickListener(v->{p.edit().putString(noteKey(today()),e.getText().toString().trim()).apply();Toast.makeText(this,"تم حفظ الملاحظة",Toast.LENGTH_SHORT).show();render();});

        addHeader(r,"التقدم والسجل","آخر الأيام التي سجلت فيها شيئًا");LinearLayout history=card();history.setPadding(dp(10),dp(4),dp(10),dp(4));add(r,history,5);List<String> dates=historyDates();if(dates.isEmpty())history.addView(tv("لا توجد بيانات سابقة لهذه المهمة بعد.",9,MUTED,false));else for(String d:dates){history.addView(historyRow(d));}

        Button edit=button("تعديل الوقت والجدولة",GREEN);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(50));ep.setMargins(0,dp(14),0,0);r.addView(edit,ep);edit.setOnClickListener(v->showEditor());
    }

    private void renderGeneral(LinearLayout r){int done=0,partial=0,notes=0;long focus=0;for(Map.Entry<String,?> e:p.getAll().entrySet()){String k=e.getKey();Object v=e.getValue();if(k.startsWith("v17_status_")){if("done".equals(String.valueOf(v)))done++;else if("partial".equals(String.valueOf(v)))partial++;}if(k.startsWith("focus_ms_"))focus+=asLong(v);if(k.startsWith("v19_note_")&&!String.valueOf(v).trim().isEmpty())notes++;}LinearLayout hero=card();hero.setPadding(dp(12),dp(12),dp(12),dp(12));add(r,hero,9);hero.addView(tv("إحصائيات كل المهمات",16,TEXT,true));LinearLayout x=row();x.addView(metric(ar(done),"مكتملة",GREEN),weight());x.addView(metric(ar(partial),"جزئية",ORANGE),weight());x.addView(metric(formatMinutes(focus),"تركيز",BLUE),weight());hero.addView(x);hero.addView(tv("ملاحظات محفوظة: "+ar(notes),9,MUTED,true));addHeader(r,"آخر الملاحظات","من جميع المهمات");LinearLayout list=card();list.setPadding(dp(10),dp(5),dp(10),dp(5));add(r,list,5);List<String> keys=new ArrayList<>();for(String k:p.getAll().keySet())if(k.startsWith("v19_note_")&&!p.getString(k,"").trim().isEmpty())keys.add(k);Collections.sort(keys,Collections.reverseOrder());if(keys.isEmpty())list.addView(tv("لا توجد ملاحظات بعد. افتح أي مهمة واكتب ملاحظة قصيرة بعد التنفيذ.",9,MUTED,false));else for(int i=0;i<Math.min(15,keys.size());i++){String k=keys.get(i),val=p.getString(k,"");TextView t=tv("• "+val,9,TEXT,false);t.setPadding(0,dp(7),0,dp(7));list.addView(t);} }

    private void showEditor(){final LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(dp(18),dp(8),dp(18),0);EditText name=input("اسم المهمة");name.setText(p.getString("v19_title_"+id,title));v.addView(name,new LinearLayout.LayoutParams(-1,dp(50)));EditText start=input("وقت البدء HH:MM مثل 07:30");int st=p.getInt("v19_start_"+id,-1);if(st>=0)start.setText(String.format(Locale.US,"%02d:%02d",st/60,st%60));v.addView(start,new LinearLayout.LayoutParams(-1,dp(50)));EditText dur=input("المدة بالدقائق");dur.setInputType(InputType.TYPE_CLASS_NUMBER);int du=p.getInt("v19_duration_"+id,-1);if(du>0)dur.setText(String.valueOf(du));v.addView(dur,new LinearLayout.LayoutParams(-1,dp(50)));
        CheckBox original=new CheckBox(this);original.setText("استخدم أيام الجدول الأصلية");original.setTextColor(TEXT);original.setTextSize(10);int oldMask=p.getInt("v19_days_"+id,0);original.setChecked(oldMask==0);v.addView(original);String[] names={"الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"};CheckBox[] days=new CheckBox[7];LinearLayout day1=row(),day2=row();for(int i=0;i<7;i++){days[i]=new CheckBox(this);days[i].setText(names[i]);days[i].setTextColor(TEXT);days[i].setTextSize(9);int cal=i+1;days[i].setChecked(oldMask!=0&&(oldMask&(1<<cal))!=0);(i<4?day1:day2).addView(days[i],new LinearLayout.LayoutParams(0,dp(42),1));}v.addView(day1);v.addView(day2);
        CheckBox monthly=new CheckBox(this);monthly.setText("مهمة شهرية في يوم محدد");monthly.setTextColor(TEXT);monthly.setTextSize(10);int md=p.getInt("v19_monthday_"+id,0);monthly.setChecked(md>0);v.addView(monthly);EditText mdField=input("يوم الشهر 1–31");mdField.setInputType(InputType.TYPE_CLASS_NUMBER);if(md>0)mdField.setText(String.valueOf(md));v.addView(mdField,new LinearLayout.LayoutParams(-1,dp(48)));
        new AlertDialog.Builder(this).setTitle("تعديل الجدولة").setView(v).setNegativeButton("إلغاء",null).setNeutralButton("استعادة الأصل",(d,w)->{SharedPreferences.Editor ed=p.edit();ed.remove("v19_title_"+id).remove("v19_start_"+id).remove("v19_duration_"+id).remove("v19_days_"+id).remove("v19_monthday_"+id).apply();Toast.makeText(this,"عادت الجدولة الأصلية",Toast.LENGTH_SHORT).show();render();}).setPositiveButton("حفظ",(d,w)->{SharedPreferences.Editor ed=p.edit();String n=name.getText().toString().trim();if(!n.isEmpty()&&!n.equals(title))ed.putString("v19_title_"+id,n);else ed.remove("v19_title_"+id);int mins=parseTime(start.getText().toString().trim());if(mins>=0)ed.putInt("v19_start_"+id,mins);else ed.remove("v19_start_"+id);int duration=parseInt(dur.getText().toString());if(duration>0)ed.putInt("v19_duration_"+id,Math.min(720,duration));else ed.remove("v19_duration_"+id);if(original.isChecked())ed.remove("v19_days_"+id);else{int mask=0;for(int i=0;i<7;i++)if(days[i].isChecked())mask|=1<<(i+1);if(mask==0)ed.remove("v19_days_"+id);else ed.putInt("v19_days_"+id,mask);}if(monthly.isChecked()){int day=parseInt(mdField.getText().toString());if(day>=1&&day<=31){ed.putInt("v19_monthday_"+id,day);ed.remove("v19_days_"+id);}}else ed.remove("v19_monthday_"+id);ed.apply();Toast.makeText(this,"تم حفظ الجدولة",Toast.LENGTH_SHORT).show();render();}).show();}

    private View historyRow(String date){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(0,dp(8),0,dp(8));String st=p.getString("v17_status_"+date+"_"+id,p.getBoolean("reward_done_"+date+"_"+id,false)?"done":"none");LinearLayout h=row();h.addView(tv(displayDate(date),10,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));h.addView(tv(statusLabel(st),9,statusColor(st),true));row.addView(h);String note=p.getString("v19_note_"+date+"_"+id,"");String result=p.getString("result_"+date+"_"+id,"");if(!note.isEmpty())row.addView(tv(note,9,MUTED,false));if(!result.isEmpty())row.addView(tv(resultSummary(result),8,MUTED,false));long f=p.getLong("focus_ms_"+date+"_"+id,0);if(f>0)row.addView(tv("تركيز فعلي: "+formatMinutes(f),8,BLUE,true));return row;}

    private void setTodayStatus(String st){String date=today(),key="v17_status_"+date+"_"+id,old=p.getString(key,p.getBoolean("reward_done_"+date+"_"+id,false)?"done":"none");int oldScore=score(old),newScore=score(st),delta=newScore-oldScore;SharedPreferences.Editor ed=p.edit().putString(key,st).putBoolean("reward_done_"+date+"_"+id,"done".equals(st));String dk="reward_day_points_"+date;ed.putInt(dk,Math.max(0,p.getInt(dk,0)+delta)).putInt("reward_domain_"+domain,Math.max(0,p.getInt("reward_domain_"+domain,0)+delta)).apply();if("done".equals(st)||"partial".equals(st))promptResultNote(st);else{Toast.makeText(this,"تم تحديث الحالة",Toast.LENGTH_SHORT).show();render();}}
    private void promptResultNote(String st){EditText e=input("ملاحظة قصيرة عن نتيجة اليوم");new AlertDialog.Builder(this).setTitle("تم تسجيل "+statusLabel(st)).setMessage("هذه الملاحظة ستظهر في سجل المهمة وتفيد مراجعة الشهر.").setView(e).setNegativeButton("بدون ملاحظة",(d,w)->render()).setPositiveButton("حفظ",(d,w)->{String x=e.getText().toString().trim();if(!x.isEmpty())p.edit().putString(noteKey(today()),x).apply();render();}).show();}

    private List<String> historyDates(){List<String> out=new ArrayList<>();for(String k:p.getAll().keySet()){String suffix="_"+id;if((k.startsWith("v17_status_")||k.startsWith("result_")||k.startsWith("v19_note_"))&&k.endsWith(suffix)){String date="";if(k.startsWith("v17_status_"))date=k.substring(11,k.length()-suffix.length());else if(k.startsWith("result_"))date=k.substring(7,k.length()-suffix.length());else date=k.substring(9,k.length()-suffix.length());if(date.matches("\\d{8}")&&!out.contains(date))out.add(date);}}Collections.sort(out,Collections.reverseOrder());if(out.size()>20)return new ArrayList<>(out.subList(0,20));return out;}
    private int done30(){return statusCount30("done");}private int partial30(){return statusCount30("partial");}private int statusCount30(String wanted){int n=0;Calendar c=Calendar.getInstance();for(int i=0;i<30;i++){String d=new SimpleDateFormat("yyyyMMdd",Locale.US).format(c.getTime());String st=p.getString("v17_status_"+d+"_"+id,p.getBoolean("reward_done_"+d+"_"+id,false)?"done":"none");if(wanted.equals(st))n++;c.add(Calendar.DAY_OF_MONTH,-1);}return n;}private long focus30(){long n=0;Calendar c=Calendar.getInstance();for(int i=0;i<30;i++){String d=new SimpleDateFormat("yyyyMMdd",Locale.US).format(c.getTime());n+=p.getLong("focus_ms_"+d+"_"+id,0);c.add(Calendar.DAY_OF_MONTH,-1);}return n;}
    private String scheduleSummary(){int st=p.getInt("v19_start_"+id,-1),du=p.getInt("v19_duration_"+id,-1),md=p.getInt("v19_monthday_"+id,0),mask=p.getInt("v19_days_"+id,0);StringBuilder s=new StringBuilder();if(st>=0)s.append("الوقت ").append(String.format(Locale.US,"%02d:%02d",st/60,st%60));else s.append("الوقت حسب الجدول الأساسي");if(du>0)s.append(" • ").append(du).append(" دقيقة");if(md>0)s.append(" • يوم ").append(md).append(" من كل شهر");else if(mask!=0)s.append(" • أيام أسبوعية مخصصة");else s.append(" • التكرار الأصلي");return s.toString();}
    private String resultSummary(String json){try{JSONObject o=new JSONObject(json);List<String>x=new ArrayList<>();java.util.Iterator<String>it=o.keys();while(it.hasNext()){String k=it.next();if(k.equals("focus_ms"))continue;String v=o.optString(k,"").trim();if(!v.isEmpty())x.add(v);}return x.isEmpty()?"":"نتيجة: "+android.text.TextUtils.join(" • ",x);}catch(Exception e){return"";}}
    private String noteKey(String date){return"v19_note_"+date+"_"+id;}private String today(){return new SimpleDateFormat("yyyyMMdd",Locale.US).format(Calendar.getInstance().getTime());}
    private int score(String st){if("done".equals(st))return points;if("partial".equals(st))return Math.max(1,points/2);return 0;}private String statusLabel(String st){if("done".equals(st))return"مكتملة";if("partial".equals(st))return"جزئية";if("cancelled".equals(st))return"ملغاة بعذر";return"لم تبدأ";}private int statusColor(String st){if("done".equals(st))return GREEN;if("partial".equals(st))return ORANGE;if("cancelled".equals(st))return MUTED;return MUTED;}private String todayStatus(){return p.getString("v17_status_"+today()+"_"+id,p.getBoolean("reward_done_"+today()+"_"+id,false)?"done":"none");}
    private int parseTime(String s){try{String[]a=s.split(":");if(a.length!=2)return-1;int h=Integer.parseInt(a[0]),m=Integer.parseInt(a[1]);if(h<0||h>23||m<0||m>59)return-1;return h*60+m;}catch(Exception e){return-1;}}private int parseInt(String s){try{return Integer.parseInt(s.trim());}catch(Exception e){return 0;}}private long asLong(Object o){if(o instanceof Number)return((Number)o).longValue();try{return Long.parseLong(String.valueOf(o));}catch(Exception e){return 0;}}
    private String displayDate(String d){try{java.util.Date x=new SimpleDateFormat("yyyyMMdd",Locale.US).parse(d);return new SimpleDateFormat("dd/MM/yyyy",Locale.US).format(x);}catch(Exception e){return d;}}private String formatMinutes(long ms){long m=ms/60000;if(m<60)return ar((int)m)+" د";return ar((int)(m/60))+"س "+ar((int)(m%60))+"د";}

    private void addHeader(LinearLayout r,String a,String b){LinearLayout h=row();h.setPadding(0,dp(15),0,dp(5));h.addView(tv(a,16,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));h.addView(tv(b,8,GREEN,true));r.addView(h);}private LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setBackground(round(CARD,16,BORDER));x.setElevation(dp(.6f));return x;}private void add(LinearLayout r,View v,int top){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(top),0,0);r.addView(v,lp);}private LinearLayout row(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.HORIZONTAL);x.setGravity(Gravity.CENTER_VERTICAL);x.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return x;}private TextView tv(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);t.setTypeface(Typeface.create("sans-serif",bold?Typeface.BOLD:Typeface.NORMAL));t.setIncludeFontPadding(false);return t;}private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(MUTED);e.setTextColor(TEXT);e.setTextSize(11);e.setPadding(dp(11),dp(8),dp(11),dp(8));e.setBackground(round(CARD,12,BORDER));e.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return e;}private Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(10);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(c,16,c));return b;}private View metric(String value,String label,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);x.setPadding(dp(3),dp(7),dp(3),dp(7));x.addView(tv(value,15,c,true));TextView l=tv(label,8,MUTED,false);l.setGravity(Gravity.CENTER);x.addView(l);return x;}private LinearLayout.LayoutParams weight(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(2),0,dp(2),0);return p;}private LinearLayout.LayoutParams weightButton(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(46),1);p.setMargins(dp(3),dp(3),dp(3),dp(3));return p;}private GradientDrawable round(int c,int rad,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(rad));g.setStroke(dp(1),stroke);return g;}private int dp(float x){return Math.round(x*getResources().getDisplayMetrics().density);}private String ar(int n){String s=String.valueOf(n),e="0123456789",a="٠١٢٣٤٥٦٧٨٩";for(int i=0;i<10;i++)s=s.replace(e.charAt(i),a.charAt(i));return s;}
}
