plugins { id 'com.android.application' }

android {
    namespace 'com.godnit.godotacademy'
    compileSdk 35

    defaultConfig {
        applicationId 'com.godnit.godotacademy'
        minSdk 23
        targetSdk 35
        versionCode 7
        versionName '6.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
